# Generated by Django 4.1.9 on 2023-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
