# Generated by Django 4.1.9 on 2023-06-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_point', '0003_alter_items_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
