# Generated by Django 4.1.9 on 2023-09-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_point', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='color',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='cpu',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='operating_System',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='resolution',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='href',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='img',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
