# Generated by Django 4.1.9 on 2023-09-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_point', '0006_laptop_color_laptop_cpu_laptop_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='color',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='operating_System',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='resolution',
            field=models.CharField(default='unknown', max_length=500),
        ),
    ]
