# Generated by Django 4.1.9 on 2023-09-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_point', '0008_remove_laptop_brand_alter_laptop_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='img',
            new_name='image',
        ),
        migrations.AddField(
            model_name='laptop',
            name='weight',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.CharField(default='Gaming Laptops', max_length=100),
        ),
    ]
