# Generated by Django 4.1.9 on 2023-09-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_point', '0009_rename_img_laptop_image_laptop_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='operating_System',
            new_name='system',
        ),
    ]
