# Generated by Django 4.1.9 on 2023-09-10 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('end_point', '0010_rename_operating_system_laptop_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop', to=settings.AUTH_USER_MODEL),
        ),
    ]
