# Generated by Django 4.1.9 on 2023-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_point', '0011_laptop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
