# Generated by Django 4.1.9 on 2023-09-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_point', '0012_alter_laptop_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='user',
            new_name='owner',
        ),
    ]
