# Generated by Django 4.1.9 on 2023-09-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_point', '0013_rename_user_laptop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='color',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='resolution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='system',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
