# Generated by Django 4.1.9 on 2023-11-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addressline',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
