# Generated by Django 4.1.9 on 2023-11-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_address_addressline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='laptop',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='formattedaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='formattedaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='formatted_adddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='laptop',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='FormattedAddress',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
