# Generated by Django 4.1.9 on 2023-12-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
