# Generated by Django 4.1.9 on 2023-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_address_first_name_alter_address_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, choices=[('        ', '       '), ('UK', 'United Kingdom'), ('US', 'United States'), ('FR', 'France'), ('GER', 'Germany')], max_length=300),
        ),
    ]
