# Generated by Django 4.1.9 on 2023-12-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='formatted_adddress',
        ),
        migrations.DeleteModel(
            name='FormattedAddress',
        ),
    ]
