# Generated by Django 4.1.9 on 2023-12-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_price_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country_code',
        ),
    ]
