# Generated by Django 4.1.9 on 2023-12-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
